version: "3.8"

volumes:
  rabbitmq_data:
  pgdata: 
  kongadata:

services:
   ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  ###################################
  # Account: The Account microservice
  ###################################
  account:
    build:
      context: ./Microservice/accountManagement
      dockerfile: Dockerfile
    image: honglixuan/account:esd
    restart: always
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Calender Complex: The Calender Complex microservice
  ###################################
  calender_complex:
    build:
      context: ./Microservice/planExerciseSchedule
      dockerfile: Dockerfile
    image: honglixuan/calender_complex:esd
    restart: always
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Calories: The Calories microservice
  ###################################
  meal:
    build:
      context: ./Microservice/getFoodInfo
      dockerfile: Dockerfile
    image: honglixuan/meal:esd
    restart: always
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Planning: The planning microservice
  ###################################
  planning:
    build:
      context: ./Microservice/createMeal
      dockerfile: Dockerfile
    image: honglixuan/planning:esd
    restart: always
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      
      
  #######################################################
  # Exercise: The exercise  microservice
  #######################################################
  exercise:
    build:
      context: ./Microservice/getExercise
      dockerfile: Dockerfile
    image: honglixuan/exercise:esd
    restart: always
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
 
 
  #######################################################
  # Recipe_complex: The recipe complex microservice
  #######################################################
  recipe_complex:
    build:
      context: ./Microservice/getRecipe
      dockerfile: Dockerfile
    image: honglixuan/recipe_complex:esd
    restart: always
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  #######################################################
  # Google: The google  microservice
  #######################################################
  google:
    build:
      context: ./Microservice/googleAuthentication
      dockerfile: Dockerfile
    image: honglixuan/google:esd
    restart: always
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  #######################################################
  # getImageDetails : The getImageDetails  microservice
  #######################################################
  getimagedetails:
    build:
      context: ./Microservice/getImageDetails
      dockerfile: Dockerfile
    image: honglixuan/getimagedetails:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

 #######################################################
  # Activity : The Activity microservice
  #######################################################
  activity:
    build:
      context: ./Microservice/logging
      dockerfile: activity.Dockerfile
    image: honglixuan/activity:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

 #######################################################
  # Error : The Error microservice
  #######################################################
  error:
    build:
      context: ./Microservice/logging
      dockerfile: error.Dockerfile
    image: honglixuan/error:esd
    restart: always
    depends_on:
        - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1


    #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:2.0.4
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: password
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:2.0.4
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: password
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-migration
    ports:
      - "8000:8000"
  
  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga
    restart: always
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: password
      DB_DATABASE: konga_db
    depends_on:
      - kong
    ports:
      - "1337:1337"
    volumes:
      - kongadata:/app/kongadata